### ISSUE TITLE
帮忙看看谢谢，用的php7 apache 和mariadb

### ISSUE THREAD

**Issue by duoduo007** [WMJonssen/Centcount-Analytics#1]
检查服务器配置：
********************************************** **** 
CPU：1核心
内存：488 MB 
磁盘：20 GB 
******************************* ******************* 

******************************* ******************* 
检查版本：
**************************** ********************** 
操作系统：Linux - \ S核心\ r在\ m - 64位
服务器上：Apache / 2.4.6（CentOS）OpenSSL / 1.0 .2k -fips PHP / 7.0.29 
PHP：7.0.29 
PHP CLI：OK 
MySQL：5.5.56 
Redis：3.2.10 
后缀：确定
******************* ******************************* 

******************* *******************************
检查MySQL连接：
********************************************** **** 
成功连接MySQL 
******************************************* ******* 

******************************************* ******* 
检查SQL模式：
*************************************** *********** 
NO_ZERO_IN_DATE =>确定
NO_ZERO_DATE =>确定
ERROR_FOR_DIVISION_BY_ZERO =>确定
NO_AUTO_CREATE_USER =>确定
NO_ENGINE_SUBSTITUTION =>确定
******************* ******************************* 

******************* ******************************* 
检查MySQL字符集：
************** ************************************ 
character_set_client：latin1 =>错误（需要“utf8”）
是character_set_connection：LATIN1 =>错误的（需要“UTF8”）
character_set_database：UTF8 =>行
character_set_results：LATIN1 =>错误的（需要“UTF8”）
被character_set_server：UTF8 =>行
character_set_system：UTF8 =>行
******** ********************** 

******** ****************************************** 
检查MySQL整理：
**** ********************************************** 
collat​​ion_connection：latin1_swedish_ci = >错误（需要“utf8_general_ci”）
collat​​ion_database：utf8_general_ci =>确定
collat​​ion_server：utf8_general_ci =>确定
****************************** ******************** 

************************** ********************
检查PHP扩展：
********************************************** **** 
session =>确定
cgi-fcgi =>错过
curl =>确定
mbstring =>确定
gd =>确定
json =>确定
mysqli =>确定
redis =>确定
************ ************ 

************ ************************************** 
检查PHP函数：
******** ****************************************** 
popen =>确定
**** ************************************** 

**** ****************************************** 
检查Redis：
* ************************************************* 
Redis 0 =>确定
Redis 1 =>确定
Redis 2 =>确定
Redis 3 =>确定
********************************************* ***** 

安装Centcount Analytics之前需要解决5个问题

有上面5个问题的时候也可以安装成功但是添加站点后把统计代码复制到网站后并不会统计，帮忙看看谢谢

**Comment by WMJonssen** [comment]
中文安装指南请参考这里：https://cn.centcount.com/doc.php?doc=%E7%99%BE%E5%A4%AB%E9%95%BF%E7%BB%9F%E8%AE%A1&article=%E5%AE%89%E8%A3%85%E7%99%BE%E5%A4%AB%E9%95%BF%E7%BB%9F%E8%AE%A1

编辑mysql配置文件来改变字符集设置，修改文件：/etc/mysql/my.cnf，将以下设置添加到 [client] 区块和 [mysqld] 区块。

> [client]
> default-character-set = utf8
> 
> [mysqld]
> default-storage-engine = INNODB
> character-set-server = utf8
> collation-server = utf8_general_ci

**Comment by duoduo007** [comment]
上面的错误就是已经在my.cnf中添加后显示的检查结果，如果不添加就会全部显示需要utf8

**Comment by WMJonssen** [comment]
你的是MariaDB,你看看目录下有哪些配置文件分别设置一下。建议你用MySQL，MariaDB我也不太熟悉。
