### ISSUE TITLE
有问题，根本统计不到数据！

### ISSUE THREAD

**Issue by cn-jiangfei** [WMJonssen/Centcount-Analytics#2]
JS一大堆报错！！

好像不太好用！

**Comment by WMJonssen** [comment]
自己部署的吧，还是用我的SaaS服务吧。

疆飞 <notifications@github.com> 于 2018年8月18日周六 上午7:54写道：

**Comment by cn-jiangfei** [comment]
为的问题，解压/ipdb/ipdb.zip 就解决了，建议站点安装后，后台去检测这文件是否存在，如果不存在后台可以给一个友好提示，这样比较OK了！

**Comment by WMJonssen** [comment]
这个下次更新可以加进去

疆飞 <notifications@github.com> 于 2018年8月18日周六 下午5:01写道：
