### ISSUE TITLE
What is the requirement for the observed website?

### ISSUE THREAD

**Issue by X-Ryl669** [WMJonssen/Centcount-Analytics#5]
In the documentation you explain how to install the dashboard.
But how do you use centcount on my website ? 
Do I need to call your code (so it must live on the same server to avoid network latency) or should I feed the database by myself ?

Can you describe this please ?

**Comment by WMJonssen** [comment]
You should install CA JS code on your pages. It works like Google Analytics. We recommend you install CA on an unique server. Latency can be ignored, Do not worry about latency. it is not big deal.
